/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_partitioned_table_load.sh operational_reporting_location_manager switches dw_timestamp dbo true true false
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh operational_reporting_location_manager configuration_types dbo false
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh operational_reporting_location_manager switch_port_interface_types dbo false
