/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods pageviewinfo dbo true 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods visitinfo dbo true 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods chatmessageinfo dbo true 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods chatcustomfieldsinfo dbo true 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods chatinfo dbo true 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods departmentoperatorxref dbo true 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods operatorinfo dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods setupiteminfo dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_countrycode dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods folderinfo dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods departmentinfo dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods foldertype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_chatstatustype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_ended_reason dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_invitestatustype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_pagetype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_chattype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_relatedtotype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_visitactiontype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_persontype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_visitstatustype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods rsl_visittype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods servicetype dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods loginactivityinfo dbo false 
/home/airflow/airflow-jobs/scripts/ods_archiving/ods_full_load.sh boldchat_ods operatorclientinfo dbo false 
