#!/bin/bash

##############################################################################
#Name           : sh_transfer_files.sh
#Description    : Shell script is used to transfer files generated by
#                 the ACG Engine to the EBI-ETL-ORD1 mount point
#Created date   : 2013/08/01
##############################################################################


LOGFILE=/mnt/ebi/acg/TransferLog/transfer_log_$(date +%Y%m%d_%T).log
MAIL_TO='DL_EBI_OPS@rackspace.com'
#MAIL_TO='tushar.gupta@rackspace.com'
MAIL_SUBJECT='Production Monitoring DATAWAREHOUSE ISSUE : Availability File Transfer Failure'

echo ' ' >> ${LOGFILE}
echo 'Availability file transfer started at    '$(date +"%m/%d/%Y %H:%M:%S") >> ${LOGFILE}
echo ' ' >> ${LOGFILE}

for SSH in /mnt/ebi/acg/csv/UpTimeCalc_Hourly_SiteScope*.csv;
do
        if [ -f "$SSH" ]; then
        mv -f "$SSH" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/sitescope/hourly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for SiteScope Hourly file at   '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSH" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved SiteScope Hourly file at   '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSH" >> ${LOGFILE}
                fi
        fi
done

for SSD in /mnt/ebi/acg/csv/UpTimeCalc_Daily_SiteScope*.csv;
do
        if [ -f "$SSD" ]; then
        mv -f "$SSD" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/sitescope/daily;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for SiteScope Daily file at    '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSD" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved SiteScope Daily file at    '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSD" >> ${LOGFILE}
                fi
        fi
done

for SSM in /mnt/ebi/acg/csv/UpTimeCalc_Monthly_SiteScope*.csv;
do
        if [ -f "$SSM" ]; then
        mv -f "$SSM" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/sitescope/monthly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for SiteScope Monthly file at  '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSM" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved SiteScope Monthly file at  '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSM" >> ${LOGFILE}
                fi
        fi
done

for RWH in /mnt/ebi/acg/csv/UpTimeCalc_Hourly_RackWatch*.csv;
do
        if [ -f "$RWH" ]; then
        mv -f "$RWH" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/rackwatch/hourly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for RackWatch Hourly file at   '$(date +"%m/%d/%Y %H:%M:%S")'     '"$RWH" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved RackWatch Hourly file at   '$(date +"%m/%d/%Y %H:%M:%S")'     '"$RWH" >> ${LOGFILE}
                fi
        fi
done

for RWD in /mnt/ebi/acg/csv/UpTimeCalc_Daily_RackWatch*.csv;
do
        if [ -f "$RWD" ]; then
        mv -f "$RWD" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/rackwatch/daily;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for RackWatch Daily file at    '$(date +"%m/%d/%Y %H:%M:%S")'     '"$RWD" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved RackWatch Daily file at    '$(date +"%m/%d/%Y %H:%M:%S")'     '"$RWD" >> ${LOGFILE}
                fi
        fi
done

for RWM in /mnt/ebi/acg/csv/UpTimeCalc_Monthly_RackWatch*.csv;
do
        if [ -f "$RWM" ]; then
        mv -f "$RWM" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/rackwatch/monthly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for RackWatch Monthly file at  '$(date +"%m/%d/%Y %H:%M:%S")'     '"$RWM" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved RackWatch Monthly file at  '$(date +"%m/%d/%Y %H:%M:%S")'     '"$RWM" >> ${LOGFILE}
                fi
        fi
done

for MH in /mnt/ebi/acg/csv/UpTimeCalc_Hourly_MaaS*.csv;
do
        if [ -f "$MH" ]; then
        mv -f "$MH" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/maas/hourly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for MaaS Hourly file at        '$(date +"%m/%d/%Y %H:%M:%S")'     '"$MH" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved MaaS Hourly file at        '$(date +"%m/%d/%Y %H:%M:%S")'     '"$MH" >> ${LOGFILE}
                fi
        fi
done

for MD in /mnt/ebi/acg/csv/UpTimeCalc_Daily_MaaS*.csv;
do
        if [ -f "$MD" ]; then
        mv -f "$MD" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/maas/daily;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for MaaS Daily file at         '$(date +"%m/%d/%Y %H:%M:%S")'     '"$MD" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved MaaS Daily file at         '$(date +"%m/%d/%Y %H:%M:%S")'     '"$MD" >> ${LOGFILE}
                fi
        fi
done

for MM in /mnt/ebi/acg/csv/UpTimeCalc_Monthly_MaaS*.csv;
do
        if [ -f "$MM" ]; then
        mv -f "$MM" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/maas/monthly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for MaaS Monthly file at       '$(date +"%m/%d/%Y %H:%M:%S")'     '"$MM" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved MaaS Monthly file at       '$(date +"%m/%d/%Y %H:%M:%S")'     '"$MM" >> ${LOGFILE}
                fi
        fi
done

for SSH in /mnt/ebi/acg/csv/UpTimeCalc_Hourly_NewRelic*.csv;
do
        if [ -f "$SSH" ]; then
        mv -f "$SSH" /mnt/ebi/EBI-ETL-PROD-01/monitoring/availability/newrelic/hourly;
                if [ "$?" != 0 ]; then
                        echo 'Transfer failed for NewRelic Hourly file at   '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSH" >> ${LOGFILE}
                        mail -s "$MAIL_SUBJECT" $MAIL_TO < ${LOGFILE}
                        exit 1
                else
                        echo 'Moved NewRelic Hourly file at   '$(date +"%m/%d/%Y %H:%M:%S")'     '"$SSH" >> ${LOGFILE}
                fi
        fi
done


echo ' ' >> ${LOGFILE}
echo 'Availability file transfer completed at    '$(date +"%m/%d/%Y %H:%M:%S") >> ${LOGFILE}
echo ' ' >> ${LOGFILE}

exit 0;
