USE clickstream;

SET hive.enforce.sorting=true;
SET hive.exec.compress.output=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.dynamic.partition=true;
SET hive.exec.max.dynamic.partitions=2000;
SET hive.execution.engine=mr;
SET hive.mapred.reduce.tasks.speculative.execution=false;
SET hive.merge.mapredfiles=true;

SET mapreduce.input.fileinputformat.split.maxsize=521000000;
SET mapreduce.job.jvm.numtasks=-1;
SET mapreduce.job.reduce.slowstart.completedmaps=0.999;
SET mapreduce.output.fileoutputformat.compress.type=BLOCK;
SET mapreduce.reduce.input.limit=-1;
SET mapreduce.task.io.sort.factor=100;
SET mapreduce.task.io.sort.mb=256;

ADD JAR  /usr/hdp/current/hive-client/lib/csv-serde-1.1.2-0.11.0-all.jar;

#create our main ods table if it doesn't already exist
create table if not exists site_visit_ods (
    accept_language  string, 
    browser  bigint, 
    browser_height  bigint, 
    browser_width  bigint, 
    campaign  string, 
    c_color  string, 
    channel  string, 
    click_action  string, 
    click_action_type  int, 
    click_context  string, 
    click_context_type  int, 
    click_sourceid  bigint, 
    click_tag  string, 
    code_ver  string, 
    color  bigint, 
    connection_type  int, 
    cookies  string,
    country  bigint, 
    ct_connect_type  string, 
    currency  string, 
    curr_factor  int, 
    curr_rate  decimal,
    cust_hit_time_gmt  bigint, 
    cust_visid  string, 
    daily_visitor  int, 
    date_time  string,
    domain  string, 
    duplicated_from  string, 
    duplicate_events  string, 
    duplicate_purchase  int, 
    evar1  string, 
    evar2  string, 
    evar3  string, 
    evar4  string, 
    evar5  string, 
    evar6  string, 
    evar7  string, 
    evar8  string, 
    evar9  string, 
    evar10  string, 
    evar11  string, 
    evar12  string, 
    evar13  string, 
    evar14  string, 
    evar15  string, 
    evar16  string, 
    evar17  string, 
    evar18  string, 
    evar19  string, 
    evar20  string, 
    evar21  string, 
    evar22  string, 
    evar23  string, 
    evar24  string, 
    evar25  string, 
    evar26  string, 
    evar27  string, 
    evar28  string, 
    evar29  string, 
    evar30  string, 
    evar31  string, 
    evar32  string, 
    evar33  string, 
    evar34  string, 
    evar35  string, 
    evar36  string, 
    evar37  string, 
    evar38  string, 
    evar39  string, 
    evar40  string, 
    evar41  string, 
    evar42  string, 
    evar43  string, 
    evar44  string, 
    evar45  string, 
    evar46  string, 
    evar47  string, 
    evar48  string, 
    evar49  string, 
    evar50  string, 
    evar51  string, 
    evar52  string, 
    evar53  string, 
    evar54  string, 
    evar55  string, 
    evar56  string, 
    evar57  string, 
    evar58  string, 
    evar59  string, 
    evar60  string, 
    evar61  string, 
    evar62  string, 
    evar63  string, 
    evar64  string, 
    evar65  string, 
    evar66  string, 
    evar67  string, 
    evar68  string, 
    evar69  string, 
    evar70  string, 
    evar71  string, 
    evar72  string, 
    evar73  string, 
    evar74  string, 
    evar75  string, 
    event_list  string, 
    exclude_hit  int, 
    first_hit_pagename  string, 
    first_hit_page_url  string, 
    first_hit_referrer  string, 
    first_hit_time_gmt  bigint, 
    geo_city  string, 
    geo_country  string, 
    geo_dma  bigint, 
    geo_region  string, 
    geo_zip  string, 
    hier1  string, 
    hier2  string, 
    hier3  string, 
    hier4  string, 
    hier5  string, 
    hitid_high  decimal,
    hitid_low  decimal,
    hit_source  int, 
    hit_time_gmt  bigint, 
    homepage  string,
    hourly_visitor  int, 
    ip  string, 
    ip2  string, 
    java_enabled  string,
    javascript  int, 
    j_jscript  string, 
    language  bigint, 
    last_hit_time_gmt  bigint, 
    last_purchase_num  bigint, 
    last_purchase_time_gmt  bigint, 
    mobile_id  bigint, 
    monthly_visitor  int, 
    mvvar1  string, 
    mvvar2  string, 
    mvvar3  string, 
    namespace  string, 
    new_visit  int, 
    os  bigint, 
    page_event  int, 
    page_event_var1  string, 
    page_event_var2  string, 
    page_event_var3  string, 
    pagename  string, 
    page_type  string, 
    page_url  string, 
    paid_search  int, 
    partner_plugins  string, 
    persistent_cookie  string, 
    plugins  string, 
    post_browser_height  bigint, 
    post_browser_width  bigint, 
    post_campaign  string, 
    post_channel  string, 
    post_cookies  string, 
    post_currency  string, 
    post_cust_hit_time_gmt  bigint, 
    post_cust_visid  int, 
    post_evar1  string, 
    post_evar2  string, 
    post_evar3  string, 
    post_evar4  string, 
    post_evar5  string, 
    post_evar6  string, 
    post_evar7  string, 
    post_evar8  string, 
    post_evar9  string, 
    post_evar10  string, 
    post_evar11  string, 
    post_evar12  string, 
    post_evar13  string, 
    post_evar14  string, 
    post_evar15  string, 
    post_evar16  string, 
    post_evar17  string, 
    post_evar18  string, 
    post_evar19  string, 
    post_evar20  string, 
    post_evar21  string, 
    post_evar22  string, 
    post_evar23  string, 
    post_evar24  string, 
    post_evar25  string, 
    post_evar26  string, 
    post_evar27  string, 
    post_evar28  string, 
    post_evar29  string, 
    post_evar30  string, 
    post_evar31  string, 
    post_evar32  string, 
    post_evar33  string, 
    post_evar34  string, 
    post_evar35  string, 
    post_evar36  string, 
    post_evar37  string, 
    post_evar38  string, 
    post_evar39  string, 
    post_evar40  string, 
    post_evar41  string, 
    post_evar42  string, 
    post_evar43  string, 
    post_evar44  string, 
    post_evar45  string, 
    post_evar46  string, 
    post_evar47  string, 
    post_evar48  string, 
    post_evar49  string, 
    post_evar50  string, 
    post_evar51  string, 
    post_evar52  string, 
    post_evar53  string, 
    post_evar54  string, 
    post_evar55  string, 
    post_evar56  string, 
    post_evar57  string, 
    post_evar58  string, 
    post_evar59  string, 
    post_evar60  string, 
    post_evar61  string, 
    post_evar62  string, 
    post_evar63  string, 
    post_evar64  string, 
    post_evar65  string, 
    post_evar66  string, 
    post_evar67  string, 
    post_evar68  string, 
    post_evar69  string, 
    post_evar70  string, 
    post_evar71  string, 
    post_evar72  string, 
    post_evar73  string, 
    post_evar74  string, 
    post_evar75  string, 
    post_event_list  string, 
    post_hier1  string, 
    post_hier2  string, 
    post_hier3  string, 
    post_hier4  string, 
    post_hier5  string, 
    post_java_enabled  string, 
    post_keywords  string, 
    post_mvvar1  string, 
    post_mvvar2  string, 
    post_mvvar3  string, 
    post_page_event  int, 
    post_page_event_var1  string, 
    post_page_event_var2  string, 
    post_page_event_var3  string, 
    post_pagename  string, 
    post_pagename_no_url  string, 
    post_page_type  string, 
    post_page_url  string, 
    post_partner_plugins  string, 
    post_persistent_cookie  string, 
    post_product_list  string, 
    post_prop1  string, 
    post_prop2  string, 
    post_prop3  string, 
    post_prop4  string, 
    post_prop5  string, 
    post_prop6  string, 
    post_prop7  string, 
    post_prop8  string, 
    post_prop9  string, 
    post_prop10  string, 
    post_prop11  string, 
    post_prop12  string, 
    post_prop13  string, 
    post_prop14  string, 
    post_prop15  string, 
    post_prop16  string, 
    post_prop17  string, 
    post_prop18  string, 
    post_prop19  string, 
    post_prop20  string, 
    post_prop21  string, 
    post_prop22  string, 
    post_prop23  string, 
    post_prop24  string, 
    post_prop25  string, 
    post_prop26  string, 
    post_prop27  string, 
    post_prop28  string, 
    post_prop29  string, 
    post_prop30  string, 
    post_prop31  string, 
    post_prop32  string, 
    post_prop33  string, 
    post_prop34  string, 
    post_prop35  string, 
    post_prop36  string, 
    post_prop37  string, 
    post_prop38  string, 
    post_prop39  string, 
    post_prop40  string, 
    post_prop41  string, 
    post_prop42  string, 
    post_prop43  string, 
    post_prop44  string, 
    post_prop45  string, 
    post_prop46  string, 
    post_prop47  string, 
    post_prop48  string, 
    post_prop49  string, 
    post_prop50  string, 
    post_prop51  string, 
    post_prop52  string, 
    post_prop53  string, 
    post_prop54  string, 
    post_prop55  string, 
    post_prop56  string, 
    post_prop57  string, 
    post_prop58  string, 
    post_prop59  string, 
    post_prop60  string, 
    post_prop61  string, 
    post_prop62  string, 
    post_prop63  string, 
    post_prop64  string, 
    post_prop65  string, 
    post_prop66  string, 
    post_prop67  string, 
    post_prop68  string, 
    post_prop69  string, 
    post_prop70  string, 
    post_prop71  string, 
    post_prop72  string, 
    post_prop73  string, 
    post_prop74  string, 
    post_prop75  string, 
    post_purchaseid  string, 
    post_referrer  string, 
    post_search_engine  bigint, 
    post_state  string, 
    post_survey  string, 
    post_tnt  string, 
    post_transactionid  string, 
    post_t_time_info  string, 
    post_visid_high  decimal,
    post_visid_low  decimal,
    post_visid_type  int, 
    post_zip  string, 
    p_plugins  string, 
    prev_page  bigint, 
    product_list  string, 
    product_merchandising  string, 
    prop1  string, 
    prop2  string, 
    prop3  string, 
    prop4  string, 
    prop5  string, 
    prop6  string, 
    prop7  string, 
    prop8  string, 
    prop9  string, 
    prop10  string, 
    prop11  string, 
    prop12  string, 
    prop13  string, 
    prop14  string, 
    prop15  string, 
    prop16  string, 
    prop17  string, 
    prop18  string, 
    prop19  string, 
    prop20  string, 
    prop21  string, 
    prop22  string, 
    prop23  string, 
    prop24  string, 
    prop25  string, 
    prop26  string, 
    prop27  string, 
    prop28  string, 
    prop29  string, 
    prop30  string, 
    prop31  string, 
    prop32  string, 
    prop33  string, 
    prop34  string, 
    prop35  string, 
    prop36  string, 
    prop37  string, 
    prop38  string, 
    prop39  string, 
    prop40  string, 
    prop41  string, 
    prop42  string, 
    prop43  string, 
    prop44  string, 
    prop45  string, 
    prop46  string, 
    prop47  string, 
    prop48  string, 
    prop49  string, 
    prop50  string, 
    prop51  string, 
    prop52  string, 
    prop53  string, 
    prop54  string, 
    prop55  string, 
    prop56  string, 
    prop57  string, 
    prop58  string, 
    prop59  string, 
    prop60  string, 
    prop61  string, 
    prop62  string, 
    prop63  string, 
    prop64  string, 
    prop65  string, 
    prop66  string, 
    prop67  string, 
    prop68  string, 
    prop69  string, 
    prop70  string, 
    prop71  string, 
    prop72  string, 
    prop73  string, 
    prop74  string, 
    prop75  string, 
    purchaseid  string, 
    quarterly_visitor  int, 
    ref_domain  string, 
    referrer  string, 
    ref_type  int, 
    resolution  bigint, 
    sampled_hit  string, 
    search_engine  bigint, 
    search_page_num  bigint, 
    secondary_hit  int, 
    service  string, 
    sourceid  bigint, 
    s_resolution  string, 
    state  string, 
    stats_server  string, 
    tnt  string, 
    tnt_post_vista  string, 
    transactionid  string, 
    truncated_hit  string, 
    t_time_info  string, 
    ua_color  string, 
    ua_os  string, 
    ua_pixels  string, 
    user_agent  string, 
    user_hash  bigint, 
    userid  bigint, 
    username  string, 
    user_server  string, 
    va_closer_detail  string, 
    va_closer_id  int, 
    va_finder_detail  string, 
    va_finder_id  int, 
    va_instance_event  int, 
    va_new_engagement  int, 
    visid_high  decimal, 
    visid_low  decimal, 
    visid_new  string, 
    visid_timestamp  bigint, 
    visid_type  int, 
    visit_keywords  string, 
    visit_num  bigint, 
    visit_page_num  bigint, 
    visit_referrer  string, 
    visit_search_engine  bigint, 
    visit_start_pagename  string, 
    visit_start_page_url  string, 
    visit_start_time_gmt  bigint, 
    weekly_visitor  int, 
    yearly_visitor  int, 
    zip  string, 
    mobileaction  string, 
    mobileappid  string, 
    mobilecampaigncontent  string, 
    mobilecampaignmedium  string, 
    mobilecampaignname  string, 
    mobilecampaignsource  string, 
    mobilecampaignterm  string, 
    mobiledayofweek  string, 
    mobiledayssincefirstuse  string, 
    mobiledayssincelastuse  string, 
    mobiledevice  string, 
    mobilehourofday  string, 
    mobileinstalldate  string, 
    mobilelaunchnumber  string, 
    mobileltv  string, 
    mobileosversion  string, 
    mobileresolution  string, 
    pointofinterest  string, 
    pointofinterestdistance  string, 
    post_mobileaction  string, 
    post_mobileappid  string, 
    post_mobilecampaigncontent  string, 
    post_mobilecampaignmedium  string, 
    post_mobilecampaignname  string, 
    post_mobilecampaignsource  string, 
    post_mobilecampaignterm  string, 
    post_mobiledayofweek  string, 
    post_mobiledayssincefirstuse  string, 
    post_mobiledayssincelastuse  string, 
    post_mobiledevice  string, 
    post_mobilehourofday  string, 
    post_mobileinstalldate  string, 
    post_mobilelaunchnumber  string, 
    post_mobileltv  string, 
    post_mobileosversion  string, 
    post_mobileresolution  string, 
    post_pointofinterest  string, 
    post_pointofinterestdistance  string, 
    socialassettrackingcode  string, 
    socialauthor  string, 
    socialaveragesentiment  string, 
    socialcontentprovider  string, 
    sociallanguage  string, 
    sociallatlong  string, 
    sociallink  string, 
    socialproperty  string, 
    socialterm  string, 
    socialtermslist  string, 
    post_socialassettrackingcode  string, 
    post_socialauthor  string, 
    post_socialaveragesentiment  string, 
    post_socialcontentprovider  string, 
    post_sociallanguage  string, 
    post_sociallatlong  string, 
    post_sociallink  string, 
    post_socialproperty  string, 
    post_socialterm  string, 
    post_socialtermslist  string, 
    video  string, 
    videoad  string, 
    videoadinpod  string, 
    videoadplayername  string, 
    videoadpod  string, 
    videochannel  string, 
    videocontenttype  string, 
    videopath  string, 
    videoplayername  string, 
    videosegment  string, 
    post_video  string, 
    post_videoad  string, 
    post_videoadinpod  string, 
    post_videoadplayername  string, 
    post_videoadpod  string, 
    post_videochannel  string, 
    post_videocontenttype  string, 
    post_videopath  string, 
    post_videoplayername  string, 
    browser_name  string, 
    browser_type  string, 
    os_name  string, 
    color_depth  string, 
    language_name  string, 
    ref_type_name  string, 
    connection_name  string, 
    resolution_name  string, 
    country_name  string, 
    javascript_version  string, 
    search_engine_name  string, 
    rec_ins_upd_dts  string
)
    PARTITIONED BY (
      dt string)
    ROW FORMAT SERDE
      'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
    STORED AS INPUTFORMAT
      'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
    OUTPUTFORMAT
      'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat';

#drop and create an empty staging table for importing CSV data
DROP TABLE IF EXISTS site_visit_ods_stg;

CREATE TABLE IF NOT EXISTS site_visit_ods_stg (
    accept_language  string, 
    browser  bigint, 
    browser_height  bigint, 
    browser_width  bigint, 
    campaign  string, 
    c_color  string, 
    channel  string, 
    click_action  string, 
    click_action_type  int, 
    click_context  string, 
    click_context_type  int, 
    click_sourceid  bigint, 
    click_tag  string, 
    code_ver  string, 
    color  bigint, 
    connection_type  int, 
    cookies  string,
    country  bigint, 
    ct_connect_type  string, 
    currency  string, 
    curr_factor  int, 
    curr_rate  decimal,
    cust_hit_time_gmt  bigint, 
    cust_visid  string, 
    daily_visitor  int, 
    date_time  string,
    domain  string, 
    duplicated_from  string, 
    duplicate_events  string, 
    duplicate_purchase  int, 
    evar1  string, 
    evar2  string, 
    evar3  string, 
    evar4  string, 
    evar5  string, 
    evar6  string, 
    evar7  string, 
    evar8  string, 
    evar9  string, 
    evar10  string, 
    evar11  string, 
    evar12  string, 
    evar13  string, 
    evar14  string, 
    evar15  string, 
    evar16  string, 
    evar17  string, 
    evar18  string, 
    evar19  string, 
    evar20  string, 
    evar21  string, 
    evar22  string, 
    evar23  string, 
    evar24  string, 
    evar25  string, 
    evar26  string, 
    evar27  string, 
    evar28  string, 
    evar29  string, 
    evar30  string, 
    evar31  string, 
    evar32  string, 
    evar33  string, 
    evar34  string, 
    evar35  string, 
    evar36  string, 
    evar37  string, 
    evar38  string, 
    evar39  string, 
    evar40  string, 
    evar41  string, 
    evar42  string, 
    evar43  string, 
    evar44  string, 
    evar45  string, 
    evar46  string, 
    evar47  string, 
    evar48  string, 
    evar49  string, 
    evar50  string, 
    evar51  string, 
    evar52  string, 
    evar53  string, 
    evar54  string, 
    evar55  string, 
    evar56  string, 
    evar57  string, 
    evar58  string, 
    evar59  string, 
    evar60  string, 
    evar61  string, 
    evar62  string, 
    evar63  string, 
    evar64  string, 
    evar65  string, 
    evar66  string, 
    evar67  string, 
    evar68  string, 
    evar69  string, 
    evar70  string, 
    evar71  string, 
    evar72  string, 
    evar73  string, 
    evar74  string, 
    evar75  string, 
    event_list  string, 
    exclude_hit  int, 
    first_hit_pagename  string, 
    first_hit_page_url  string, 
    first_hit_referrer  string, 
    first_hit_time_gmt  bigint, 
    geo_city  string, 
    geo_country  string, 
    geo_dma  bigint, 
    geo_region  string, 
    geo_zip  string, 
    hier1  string, 
    hier2  string, 
    hier3  string, 
    hier4  string, 
    hier5  string, 
    hitid_high  decimal,
    hitid_low  decimal,
    hit_source  int, 
    hit_time_gmt  bigint, 
    homepage  string,
    hourly_visitor  int, 
    ip  string, 
    ip2  string, 
    java_enabled  string,
    javascript  int, 
    j_jscript  string, 
    language  bigint, 
    last_hit_time_gmt  bigint, 
    last_purchase_num  bigint, 
    last_purchase_time_gmt  bigint, 
    mobile_id  bigint, 
    monthly_visitor  int, 
    mvvar1  string, 
    mvvar2  string, 
    mvvar3  string, 
    namespace  string, 
    new_visit  int, 
    os  bigint, 
    page_event  int, 
    page_event_var1  string, 
    page_event_var2  string, 
    page_event_var3  string, 
    pagename  string, 
    page_type  string, 
    page_url  string, 
    paid_search  int, 
    partner_plugins  string, 
    persistent_cookie  string, 
    plugins  string, 
    post_browser_height  bigint, 
    post_browser_width  bigint, 
    post_campaign  string, 
    post_channel  string, 
    post_cookies  string, 
    post_currency  string, 
    post_cust_hit_time_gmt  bigint, 
    post_cust_visid  int, 
    post_evar1  string, 
    post_evar2  string, 
    post_evar3  string, 
    post_evar4  string, 
    post_evar5  string, 
    post_evar6  string, 
    post_evar7  string, 
    post_evar8  string, 
    post_evar9  string, 
    post_evar10  string, 
    post_evar11  string, 
    post_evar12  string, 
    post_evar13  string, 
    post_evar14  string, 
    post_evar15  string, 
    post_evar16  string, 
    post_evar17  string, 
    post_evar18  string, 
    post_evar19  string, 
    post_evar20  string, 
    post_evar21  string, 
    post_evar22  string, 
    post_evar23  string, 
    post_evar24  string, 
    post_evar25  string, 
    post_evar26  string, 
    post_evar27  string, 
    post_evar28  string, 
    post_evar29  string, 
    post_evar30  string, 
    post_evar31  string, 
    post_evar32  string, 
    post_evar33  string, 
    post_evar34  string, 
    post_evar35  string, 
    post_evar36  string, 
    post_evar37  string, 
    post_evar38  string, 
    post_evar39  string, 
    post_evar40  string, 
    post_evar41  string, 
    post_evar42  string, 
    post_evar43  string, 
    post_evar44  string, 
    post_evar45  string, 
    post_evar46  string, 
    post_evar47  string, 
    post_evar48  string, 
    post_evar49  string, 
    post_evar50  string, 
    post_evar51  string, 
    post_evar52  string, 
    post_evar53  string, 
    post_evar54  string, 
    post_evar55  string, 
    post_evar56  string, 
    post_evar57  string, 
    post_evar58  string, 
    post_evar59  string, 
    post_evar60  string, 
    post_evar61  string, 
    post_evar62  string, 
    post_evar63  string, 
    post_evar64  string, 
    post_evar65  string, 
    post_evar66  string, 
    post_evar67  string, 
    post_evar68  string, 
    post_evar69  string, 
    post_evar70  string, 
    post_evar71  string, 
    post_evar72  string, 
    post_evar73  string, 
    post_evar74  string, 
    post_evar75  string, 
    post_event_list  string, 
    post_hier1  string, 
    post_hier2  string, 
    post_hier3  string, 
    post_hier4  string, 
    post_hier5  string, 
    post_java_enabled  string, 
    post_keywords  string, 
    post_mvvar1  string, 
    post_mvvar2  string, 
    post_mvvar3  string, 
    post_page_event  int, 
    post_page_event_var1  string, 
    post_page_event_var2  string, 
    post_page_event_var3  string, 
    post_pagename  string, 
    post_pagename_no_url  string, 
    post_page_type  string, 
    post_page_url  string, 
    post_partner_plugins  string, 
    post_persistent_cookie  string, 
    post_product_list  string, 
    post_prop1  string, 
    post_prop2  string, 
    post_prop3  string, 
    post_prop4  string, 
    post_prop5  string, 
    post_prop6  string, 
    post_prop7  string, 
    post_prop8  string, 
    post_prop9  string, 
    post_prop10  string, 
    post_prop11  string, 
    post_prop12  string, 
    post_prop13  string, 
    post_prop14  string, 
    post_prop15  string, 
    post_prop16  string, 
    post_prop17  string, 
    post_prop18  string, 
    post_prop19  string, 
    post_prop20  string, 
    post_prop21  string, 
    post_prop22  string, 
    post_prop23  string, 
    post_prop24  string, 
    post_prop25  string, 
    post_prop26  string, 
    post_prop27  string, 
    post_prop28  string, 
    post_prop29  string, 
    post_prop30  string, 
    post_prop31  string, 
    post_prop32  string, 
    post_prop33  string, 
    post_prop34  string, 
    post_prop35  string, 
    post_prop36  string, 
    post_prop37  string, 
    post_prop38  string, 
    post_prop39  string, 
    post_prop40  string, 
    post_prop41  string, 
    post_prop42  string, 
    post_prop43  string, 
    post_prop44  string, 
    post_prop45  string, 
    post_prop46  string, 
    post_prop47  string, 
    post_prop48  string, 
    post_prop49  string, 
    post_prop50  string, 
    post_prop51  string, 
    post_prop52  string, 
    post_prop53  string, 
    post_prop54  string, 
    post_prop55  string, 
    post_prop56  string, 
    post_prop57  string, 
    post_prop58  string, 
    post_prop59  string, 
    post_prop60  string, 
    post_prop61  string, 
    post_prop62  string, 
    post_prop63  string, 
    post_prop64  string, 
    post_prop65  string, 
    post_prop66  string, 
    post_prop67  string, 
    post_prop68  string, 
    post_prop69  string, 
    post_prop70  string, 
    post_prop71  string, 
    post_prop72  string, 
    post_prop73  string, 
    post_prop74  string, 
    post_prop75  string, 
    post_purchaseid  string, 
    post_referrer  string, 
    post_search_engine  bigint, 
    post_state  string, 
    post_survey  string, 
    post_tnt  string, 
    post_transactionid  string, 
    post_t_time_info  string, 
    post_visid_high  decimal,
    post_visid_low  decimal,
    post_visid_type  int, 
    post_zip  string, 
    p_plugins  string, 
    prev_page  bigint, 
    product_list  string, 
    product_merchandising  string, 
    prop1  string, 
    prop2  string, 
    prop3  string, 
    prop4  string, 
    prop5  string, 
    prop6  string, 
    prop7  string, 
    prop8  string, 
    prop9  string, 
    prop10  string, 
    prop11  string, 
    prop12  string, 
    prop13  string, 
    prop14  string, 
    prop15  string, 
    prop16  string, 
    prop17  string, 
    prop18  string, 
    prop19  string, 
    prop20  string, 
    prop21  string, 
    prop22  string, 
    prop23  string, 
    prop24  string, 
    prop25  string, 
    prop26  string, 
    prop27  string, 
    prop28  string, 
    prop29  string, 
    prop30  string, 
    prop31  string, 
    prop32  string, 
    prop33  string, 
    prop34  string, 
    prop35  string, 
    prop36  string, 
    prop37  string, 
    prop38  string, 
    prop39  string, 
    prop40  string, 
    prop41  string, 
    prop42  string, 
    prop43  string, 
    prop44  string, 
    prop45  string, 
    prop46  string, 
    prop47  string, 
    prop48  string, 
    prop49  string, 
    prop50  string, 
    prop51  string, 
    prop52  string, 
    prop53  string, 
    prop54  string, 
    prop55  string, 
    prop56  string, 
    prop57  string, 
    prop58  string, 
    prop59  string, 
    prop60  string, 
    prop61  string, 
    prop62  string, 
    prop63  string, 
    prop64  string, 
    prop65  string, 
    prop66  string, 
    prop67  string, 
    prop68  string, 
    prop69  string, 
    prop70  string, 
    prop71  string, 
    prop72  string, 
    prop73  string, 
    prop74  string, 
    prop75  string, 
    purchaseid  string, 
    quarterly_visitor  int, 
    ref_domain  string, 
    referrer  string, 
    ref_type  int, 
    resolution  bigint, 
    sampled_hit  string, 
    search_engine  bigint, 
    search_page_num  bigint, 
    secondary_hit  int, 
    service  string, 
    sourceid  bigint, 
    s_resolution  string, 
    state  string, 
    stats_server  string, 
    tnt  string, 
    tnt_post_vista  string, 
    transactionid  string, 
    truncated_hit  string, 
    t_time_info  string, 
    ua_color  string, 
    ua_os  string, 
    ua_pixels  string, 
    user_agent  string, 
    user_hash  bigint, 
    userid  bigint, 
    username  string, 
    user_server  string, 
    va_closer_detail  string, 
    va_closer_id  int, 
    va_finder_detail  string, 
    va_finder_id  int, 
    va_instance_event  int, 
    va_new_engagement  int, 
    visid_high  decimal, 
    visid_low  decimal, 
    visid_new  string, 
    visid_timestamp  bigint, 
    visid_type  int, 
    visit_keywords  string, 
    visit_num  bigint, 
    visit_page_num  bigint, 
    visit_referrer  string, 
    visit_search_engine  bigint, 
    visit_start_pagename  string, 
    visit_start_page_url  string, 
    visit_start_time_gmt  bigint, 
    weekly_visitor  int, 
    yearly_visitor  int, 
    zip  string, 
    mobileaction  string, 
    mobileappid  string, 
    mobilecampaigncontent  string, 
    mobilecampaignmedium  string, 
    mobilecampaignname  string, 
    mobilecampaignsource  string, 
    mobilecampaignterm  string, 
    mobiledayofweek  string, 
    mobiledayssincefirstuse  string, 
    mobiledayssincelastuse  string, 
    mobiledevice  string, 
    mobilehourofday  string, 
    mobileinstalldate  string, 
    mobilelaunchnumber  string, 
    mobileltv  string, 
    mobileosversion  string, 
    mobileresolution  string, 
    pointofinterest  string, 
    pointofinterestdistance  string, 
    post_mobileaction  string, 
    post_mobileappid  string, 
    post_mobilecampaigncontent  string, 
    post_mobilecampaignmedium  string, 
    post_mobilecampaignname  string, 
    post_mobilecampaignsource  string, 
    post_mobilecampaignterm  string, 
    post_mobiledayofweek  string, 
    post_mobiledayssincefirstuse  string, 
    post_mobiledayssincelastuse  string, 
    post_mobiledevice  string, 
    post_mobilehourofday  string, 
    post_mobileinstalldate  string, 
    post_mobilelaunchnumber  string, 
    post_mobileltv  string, 
    post_mobileosversion  string, 
    post_mobileresolution  string, 
    post_pointofinterest  string, 
    post_pointofinterestdistance  string, 
    socialassettrackingcode  string, 
    socialauthor  string, 
    socialaveragesentiment  string, 
    socialcontentprovider  string, 
    sociallanguage  string, 
    sociallatlong  string, 
    sociallink  string, 
    socialproperty  string, 
    socialterm  string, 
    socialtermslist  string, 
    post_socialassettrackingcode  string, 
    post_socialauthor  string, 
    post_socialaveragesentiment  string, 
    post_socialcontentprovider  string, 
    post_sociallanguage  string, 
    post_sociallatlong  string, 
    post_sociallink  string, 
    post_socialproperty  string, 
    post_socialterm  string, 
    post_socialtermslist  string, 
    video  string, 
    videoad  string, 
    videoadinpod  string, 
    videoadplayername  string, 
    videoadpod  string, 
    videochannel  string, 
    videocontenttype  string, 
    videopath  string, 
    videoplayername  string, 
    videosegment  string, 
    post_video  string, 
    post_videoad  string, 
    post_videoadinpod  string, 
    post_videoadplayername  string, 
    post_videoadpod  string, 
    post_videochannel  string, 
    post_videocontenttype  string, 
    post_videopath  string, 
    post_videoplayername  string, 
    browser_name  string, 
    browser_type  string, 
    os_name  string, 
    color_depth  string, 
    language_name  string, 
    ref_type_name  string, 
    connection_name  string, 
    resolution_name  string, 
    country_name  string, 
    javascript_version  string, 
    search_engine_name  string, 
    rec_ins_upd_dts  string
)
ROW FORMAT SERDE 'com.bizo.hive.serde.csv.CSVSerde';

!rm -rf /user/clickstream/site_visit_ods
!sqoop import --connect jdbc:postgresql://db.acg.corp.rackspace.com/acg_staging --username davi4935 -P --table site_visit_stg_ods_1 --num-mappers 1 --target-dir /user/clickstream/site_visit_ods  --fields-terminated-by , --escaped-by \\\ --enclosed-by '\"'  --hive-drop-import-delims -- --schema mktg_staging --table-hints NOLOCK

LOAD DATA INPATH '/user/clickstream/site_visit_ods/*.csv' INTO TABLE site_visit_ods_stg;

FROM site_visit_ods_stg stg
INSERT OVERWRITE TABLE site_visit_ods PARTITION(dt)
  SELECT
    stg.accept_language, 
    stg.browser, 
    stg.browser_height, 
    stg.browser_width, 
    stg.campaign, 
    stg.c_color, 
    stg.channel, 
    stg.click_action, 
    stg.click_action_type, 
    stg.click_context, 
    stg.click_context_type, 
    stg.click_sourceid, 
    stg.click_tag, 
    stg.code_ver, 
    stg.color, 
    stg.connection_type, 
    stg.cookies,
    stg.country, 
    stg.ct_connect_type, 
    stg.currency, 
    stg.curr_factor, 
    stg.curr_rate,
    stg.cust_hit_time_gmt, 
    stg.cust_visid, 
    stg.daily_visitor, 
    stg.date_time,
    stg.domain, 
    stg.duplicated_from, 
    stg.duplicate_events, 
    stg.duplicate_purchase, 
    stg.evar1, 
    stg.evar2, 
    stg.evar3, 
    stg.evar4, 
    stg.evar5, 
    stg.evar6, 
    stg.evar7, 
    stg.evar8, 
    stg.evar9, 
    stg.evar10, 
    stg.evar11, 
    stg.evar12, 
    stg.evar13, 
    stg.evar14, 
    stg.evar15, 
    stg.evar16, 
    stg.evar17, 
    stg.evar18, 
    stg.evar19, 
    stg.evar20, 
    stg.evar21, 
    stg.evar22, 
    stg.evar23, 
    stg.evar24, 
    stg.evar25, 
    stg.evar26, 
    stg.evar27, 
    stg.evar28, 
    stg.evar29, 
    stg.evar30, 
    stg.evar31, 
    stg.evar32, 
    stg.evar33, 
    stg.evar34, 
    stg.evar35, 
    stg.evar36, 
    stg.evar37, 
    stg.evar38, 
    stg.evar39, 
    stg.evar40, 
    stg.evar41, 
    stg.evar42, 
    stg.evar43, 
    stg.evar44, 
    stg.evar45, 
    stg.evar46, 
    stg.evar47, 
    stg.evar48, 
    stg.evar49, 
    stg.evar50, 
    stg.evar51, 
    stg.evar52, 
    stg.evar53, 
    stg.evar54, 
    stg.evar55, 
    stg.evar56, 
    stg.evar57, 
    stg.evar58, 
    stg.evar59, 
    stg.evar60, 
    stg.evar61, 
    stg.evar62, 
    stg.evar63, 
    stg.evar64, 
    stg.evar65, 
    stg.evar66, 
    stg.evar67, 
    stg.evar68, 
    stg.evar69, 
    stg.evar70, 
    stg.evar71, 
    stg.evar72, 
    stg.evar73, 
    stg.evar74, 
    stg.evar75, 
    stg.event_list, 
    stg.exclude_hit, 
    stg.first_hit_pagename, 
    stg.first_hit_page_url, 
    stg.first_hit_referrer, 
    stg.first_hit_time_gmt, 
    stg.geo_city, 
    stg.geo_country, 
    stg.geo_dma, 
    stg.geo_region, 
    stg.geo_zip, 
    stg.hier1, 
    stg.hier2, 
    stg.hier3, 
    stg.hier4, 
    stg.hier5, 
    stg.hitid_high,
    stg.hitid_low,
    stg.hit_source, 
    stg.hit_time_gmt, 
    stg.homepage,
    stg.hourly_visitor, 
    stg.ip, 
    stg.ip2, 
    stg.java_enabled,
    stg.javascript, 
    stg.j_jscript, 
    stg.language, 
    stg.last_hit_time_gmt, 
    stg.last_purchase_num, 
    stg.last_purchase_time_gmt, 
    stg.mobile_id, 
    stg.monthly_visitor, 
    stg.mvvar1, 
    stg.mvvar2, 
    stg.mvvar3, 
    stg.namespace, 
    stg.new_visit, 
    stg.os, 
    stg.page_event, 
    stg.page_event_var1, 
    stg.page_event_var2, 
    stg.page_event_var3, 
    stg.pagename, 
    stg.page_type, 
    stg.page_url, 
    stg.paid_search, 
    stg.partner_plugins, 
    stg.persistent_cookie, 
    stg.plugins, 
    stg.post_browser_height, 
    stg.post_browser_width, 
    stg.post_campaign, 
    stg.post_channel, 
    stg.post_cookies, 
    stg.post_currency, 
    stg.post_cust_hit_time_gmt, 
    stg.post_cust_visid, 
    stg.post_evar1, 
    stg.post_evar2, 
    stg.post_evar3, 
    stg.post_evar4, 
    stg.post_evar5, 
    stg.post_evar6, 
    stg.post_evar7, 
    stg.post_evar8, 
    stg.post_evar9, 
    stg.post_evar10, 
    stg.post_evar11, 
    stg.post_evar12, 
    stg.post_evar13, 
    stg.post_evar14, 
    stg.post_evar15, 
    stg.post_evar16, 
    stg.post_evar17, 
    stg.post_evar18, 
    stg.post_evar19, 
    stg.post_evar20, 
    stg.post_evar21, 
    stg.post_evar22, 
    stg.post_evar23, 
    stg.post_evar24, 
    stg.post_evar25, 
    stg.post_evar26, 
    stg.post_evar27, 
    stg.post_evar28, 
    stg.post_evar29, 
    stg.post_evar30, 
    stg.post_evar31, 
    stg.post_evar32, 
    stg.post_evar33, 
    stg.post_evar34, 
    stg.post_evar35, 
    stg.post_evar36, 
    stg.post_evar37, 
    stg.post_evar38, 
    stg.post_evar39, 
    stg.post_evar40, 
    stg.post_evar41, 
    stg.post_evar42, 
    stg.post_evar43, 
    stg.post_evar44, 
    stg.post_evar45, 
    stg.post_evar46, 
    stg.post_evar47, 
    stg.post_evar48, 
    stg.post_evar49, 
    stg.post_evar50, 
    stg.post_evar51, 
    stg.post_evar52, 
    stg.post_evar53, 
    stg.post_evar54, 
    stg.post_evar55, 
    stg.post_evar56, 
    stg.post_evar57, 
    stg.post_evar58, 
    stg.post_evar59, 
    stg.post_evar60, 
    stg.post_evar61, 
    stg.post_evar62, 
    stg.post_evar63, 
    stg.post_evar64, 
    stg.post_evar65, 
    stg.post_evar66, 
    stg.post_evar67, 
    stg.post_evar68, 
    stg.post_evar69, 
    stg.post_evar70, 
    stg.post_evar71, 
    stg.post_evar72, 
    stg.post_evar73, 
    stg.post_evar74, 
    stg.post_evar75, 
    stg.post_event_list, 
    stg.post_hier1, 
    stg.post_hier2, 
    stg.post_hier3, 
    stg.post_hier4, 
    stg.post_hier5, 
    stg.post_java_enabled, 
    stg.post_keywords, 
    stg.post_mvvar1, 
    stg.post_mvvar2, 
    stg.post_mvvar3, 
    stg.post_page_event, 
    stg.post_page_event_var1, 
    stg.post_page_event_var2, 
    stg.post_page_event_var3, 
    stg.post_pagename, 
    stg.post_pagename_no_url, 
    stg.post_page_type, 
    stg.post_page_url, 
    stg.post_partner_plugins, 
    stg.post_persistent_cookie, 
    stg.post_product_list, 
    stg.post_prop1, 
    stg.post_prop2, 
    stg.post_prop3, 
    stg.post_prop4, 
    stg.post_prop5, 
    stg.post_prop6, 
    stg.post_prop7, 
    stg.post_prop8, 
    stg.post_prop9, 
    stg.post_prop10, 
    stg.post_prop11, 
    stg.post_prop12, 
    stg.post_prop13, 
    stg.post_prop14, 
    stg.post_prop15, 
    stg.post_prop16, 
    stg.post_prop17, 
    stg.post_prop18, 
    stg.post_prop19, 
    stg.post_prop20, 
    stg.post_prop21, 
    stg.post_prop22, 
    stg.post_prop23, 
    stg.post_prop24, 
    stg.post_prop25, 
    stg.post_prop26, 
    stg.post_prop27, 
    stg.post_prop28, 
    stg.post_prop29, 
    stg.post_prop30, 
    stg.post_prop31, 
    stg.post_prop32, 
    stg.post_prop33, 
    stg.post_prop34, 
    stg.post_prop35, 
    stg.post_prop36, 
    stg.post_prop37, 
    stg.post_prop38, 
    stg.post_prop39, 
    stg.post_prop40, 
    stg.post_prop41, 
    stg.post_prop42, 
    stg.post_prop43, 
    stg.post_prop44, 
    stg.post_prop45, 
    stg.post_prop46, 
    stg.post_prop47, 
    stg.post_prop48, 
    stg.post_prop49, 
    stg.post_prop50, 
    stg.post_prop51, 
    stg.post_prop52, 
    stg.post_prop53, 
    stg.post_prop54, 
    stg.post_prop55, 
    stg.post_prop56, 
    stg.post_prop57, 
    stg.post_prop58, 
    stg.post_prop59, 
    stg.post_prop60, 
    stg.post_prop61, 
    stg.post_prop62, 
    stg.post_prop63, 
    stg.post_prop64, 
    stg.post_prop65, 
    stg.post_prop66, 
    stg.post_prop67, 
    stg.post_prop68, 
    stg.post_prop69, 
    stg.post_prop70, 
    stg.post_prop71, 
    stg.post_prop72, 
    stg.post_prop73, 
    stg.post_prop74, 
    stg.post_prop75, 
    stg.post_purchaseid, 
    stg.post_referrer, 
    stg.post_search_engine, 
    stg.post_state, 
    stg.post_survey, 
    stg.post_tnt, 
    stg.post_transactionid, 
    stg.post_t_time_info, 
    stg.post_visid_high,
    stg.post_visid_low,
    stg.post_visid_type, 
    stg.post_zip, 
    stg.p_plugins, 
    stg.prev_page, 
    stg.product_list, 
    stg.product_merchandising, 
    stg.prop1, 
    stg.prop2, 
    stg.prop3, 
    stg.prop4, 
    stg.prop5, 
    stg.prop6, 
    stg.prop7, 
    stg.prop8, 
    stg.prop9, 
    stg.prop10, 
    stg.prop11, 
    stg.prop12, 
    stg.prop13, 
    stg.prop14, 
    stg.prop15, 
    stg.prop16, 
    stg.prop17, 
    stg.prop18, 
    stg.prop19, 
    stg.prop20, 
    stg.prop21, 
    stg.prop22, 
    stg.prop23, 
    stg.prop24, 
    stg.prop25, 
    stg.prop26, 
    stg.prop27, 
    stg.prop28, 
    stg.prop29, 
    stg.prop30, 
    stg.prop31, 
    stg.prop32, 
    stg.prop33, 
    stg.prop34, 
    stg.prop35, 
    stg.prop36, 
    stg.prop37, 
    stg.prop38, 
    stg.prop39, 
    stg.prop40, 
    stg.prop41, 
    stg.prop42, 
    stg.prop43, 
    stg.prop44, 
    stg.prop45, 
    stg.prop46, 
    stg.prop47, 
    stg.prop48, 
    stg.prop49, 
    stg.prop50, 
    stg.prop51, 
    stg.prop52, 
    stg.prop53, 
    stg.prop54, 
    stg.prop55, 
    stg.prop56, 
    stg.prop57, 
    stg.prop58, 
    stg.prop59, 
    stg.prop60, 
    stg.prop61, 
    stg.prop62, 
    stg.prop63, 
    stg.prop64, 
    stg.prop65, 
    stg.prop66, 
    stg.prop67, 
    stg.prop68, 
    stg.prop69, 
    stg.prop70, 
    stg.prop71, 
    stg.prop72, 
    stg.prop73, 
    stg.prop74, 
    stg.prop75, 
    stg.purchaseid, 
    stg.quarterly_visitor, 
    stg.ref_domain, 
    stg.referrer, 
    stg.ref_type, 
    stg.resolution, 
    stg.sampled_hit, 
    stg.search_engine, 
    stg.search_page_num, 
    stg.secondary_hit, 
    stg.service, 
    stg.sourceid, 
    stg.s_resolution, 
    stg.state, 
    stg.stats_server, 
    stg.tnt, 
    stg.tnt_post_vista, 
    stg.transactionid, 
    stg.truncated_hit, 
    stg.t_time_info, 
    stg.ua_color, 
    stg.ua_os, 
    stg.ua_pixels, 
    stg.user_agent, 
    stg.user_hash, 
    stg.userid, 
    stg.username, 
    stg.user_server, 
    stg.va_closer_detail, 
    stg.va_closer_id, 
    stg.va_finder_detail, 
    stg.va_finder_id, 
    stg.va_instance_event, 
    stg.va_new_engagement, 
    stg.visid_high, 
    stg.visid_low, 
    stg.visid_new, 
    stg.visid_timestamp, 
    stg.visid_type, 
    stg.visit_keywords, 
    stg.visit_num, 
    stg.visit_page_num, 
    stg.visit_referrer, 
    stg.visit_search_engine, 
    stg.visit_start_pagename, 
    stg.visit_start_page_url, 
    stg.visit_start_time_gmt, 
    stg.weekly_visitor, 
    stg.yearly_visitor, 
    stg.zip, 
    stg.mobileaction, 
    stg.mobileappid, 
    stg.mobilecampaigncontent, 
    stg.mobilecampaignmedium, 
    stg.mobilecampaignname, 
    stg.mobilecampaignsource, 
    stg.mobilecampaignterm, 
    stg.mobiledayofweek, 
    stg.mobiledayssincefirstuse, 
    stg.mobiledayssincelastuse, 
    stg.mobiledevice, 
    stg.mobilehourofday, 
    stg.mobileinstalldate, 
    stg.mobilelaunchnumber, 
    stg.mobileltv, 
    stg.mobileosversion, 
    stg.mobileresolution, 
    stg.pointofinterest, 
    stg.pointofinterestdistance, 
    stg.post_mobileaction, 
    stg.post_mobileappid, 
    stg.post_mobilecampaigncontent, 
    stg.post_mobilecampaignmedium, 
    stg.post_mobilecampaignname, 
    stg.post_mobilecampaignsource, 
    stg.post_mobilecampaignterm, 
    stg.post_mobiledayofweek, 
    stg.post_mobiledayssincefirstuse, 
    stg.post_mobiledayssincelastuse, 
    stg.post_mobiledevice, 
    stg.post_mobilehourofday, 
    stg.post_mobileinstalldate, 
    stg.post_mobilelaunchnumber, 
    stg.post_mobileltv, 
    stg.post_mobileosversion, 
    stg.post_mobileresolution, 
    stg.post_pointofinterest, 
    stg.post_pointofinterestdistance, 
    stg.socialassettrackingcode, 
    stg.socialauthor, 
    stg.socialaveragesentiment, 
    stg.socialcontentprovider, 
    stg.sociallanguage, 
    stg.sociallatlong, 
    stg.sociallink, 
    stg.socialproperty, 
    stg.socialterm, 
    stg.socialtermslist, 
    stg.post_socialassettrackingcode, 
    stg.post_socialauthor, 
    stg.post_socialaveragesentiment, 
    stg.post_socialcontentprovider, 
    stg.post_sociallanguage, 
    stg.post_sociallatlong, 
    stg.post_sociallink, 
    stg.post_socialproperty, 
    stg.post_socialterm, 
    stg.post_socialtermslist, 
    stg.video, 
    stg.videoad, 
    stg.videoadinpod, 
    stg.videoadplayername, 
    stg.videoadpod, 
    stg.videochannel, 
    stg.videocontenttype, 
    stg.videopath, 
    stg.videoplayername, 
    stg.videosegment, 
    stg.post_video, 
    stg.post_videoad, 
    stg.post_videoadinpod, 
    stg.post_videoadplayername, 
    stg.post_videoadpod, 
    stg.post_videochannel, 
    stg.post_videocontenttype, 
    stg.post_videopath, 
    stg.post_videoplayername, 
    stg.browser_name, 
    stg.browser_type, 
    stg.os_name, 
    stg.color_depth, 
    stg.language_name, 
    stg.ref_type_name, 
    stg.connection_name, 
    stg.resolution_name, 
    stg.country_name, 
    stg.javascript_version, 
    stg.search_engine_name, 
    stg.rec_ins_upd_dts,
    substring(stg.date_time, 1, 10) as dt
DISTRIBUTE BY dt
;

DROP TABLE site_visit_ods_stg;
